### PR TITLE
Fix build against p8-platform in Jarvis branch

### PR DESCRIPTION
**Pull request by koenkooi**
Cherry-pick the 2 fixes from the master branch.

### CODE REVIEW

**Comment by Montellese** [comment]
On kodi's Jarvis branch we point to commits for {{platform}} and {{kodi-platform}} which are both before the rename to {{p8-platform}} so this will not make it into those builds anyway. AFAIK we want to build and release Jarvis with the old {{platform}} so I don't think that this is right.

@opdenkamp @wsnipex @MartijnKaijser: what is the plan for Jarvis?

**Comment by koenkooi** [comment]
The issue I'm running into is that libcec/master is using p8-platform, which creates the mismatch. I can patch kodi-platform and pvr-hts locally (which I have done) _or_ use an almost year old version of libcec (which I want to avoid).

**Comment by opdenkamp** [comment]
I've done the renaming so that both can be linked without causing collisions, so it doesn't matter much. The idea behind that is that it's used by almost all add-ons and that you don't want to update them all yourself, but have add-on devs do it when they want to.

@koenkooi how is that causing issues?

**Comment by MartijnKaijser** [comment]
See https://github.com/xbmc/kodi-platform/pull/21
@Montellese already said we build against a specific version. Also on all jarvis addons we use that specific version.
I rather not start messing with this.

I think that would also mean have to patch all addons as well?

**Comment by opdenkamp** [comment]
I don't get what you mean. The two libs can coexist, and add-on devs can mess around with whatever they like, as long as it's in their add-on?

**Comment by wsnipex** [comment]
I've pushed a Jarvis branch to kodi-platform, which should be used together with Jarvis branches of all addons as well as (p8)platform.
https://github.com/xbmc/kodi-platform/commits/Jarvis

**Comment by wsnipex** [comment]
to clariy, this PR is wrong. If you want to build addons for Kodi 16 use Jarvis branches in all libs and addons

**Pull request closed without merging**
