### PR TITLE
Added dlfcn-win32 and os-threads for windows

### PR DESCRIPTION
**Pull request by AchimTuran**
@Montellese or @opdenkamp 
This fixes the build of AudioDSP and probably other binary add-ons, the build under windows fails, because of linking errors with the missing dlfcn-win32 functions.

### CODE REVIEW

**Comment by Montellese** [comment]
Shouldn't this be part of the platform library? I didn't add these myself so they must have been lost during the split of kodi-platform and platform. @opdenkamp any idea?

**Comment by Montellese** [comment]
Yup see https://github.com/Pulse-Eight/platform/tree/master/src/windows the files are already part of the `libplatform` library so this is certainly not right. And the`CMakeLists.txt looks ok as well, see https://github.com/Pulse-Eight/platform/blob/master/CMakeLists.txt#L21 and https://github.com/Pulse-Eight/platform/blob/master/CMakeLists.txt#L27.

Could you provide the output from one of your failed builds?

**Comment by opdenkamp** [comment]
@Montellese sorry, I'll be Bob the Builder for the next 2 weeks, can't check now.

**Comment by AchimTuran** [comment]
@Montellese 
Sorry one mistake from me I didn't see that there are now two libraries (kodiplatform and platform). It's a little bit confusing.

> Could you provide the output from one of your failed builds?

The linking from [adsp.biquad.filters-fork](https://github.com/AchimTuran/adsp.biquad.filters-fork) with platform fails:
Linking CXX shared library adsp.biquad.filters.dll
   Bibliothek "adsp.biquad.filters.lib" und Objekt "adsp.biquad.filters.exp" wer
den erstellt.

client.cpp.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "" void \* __cdecl dlopen(char const *,int)" (?dlopen@@YAPAXPBDH@Z)" in Funktion ""p ublic: bool __thiscall CHelper_libKODI_adsp::RegisterMe(void *)" (?RegisterMe@CHelper_libKODI_adsp@@QAE_NPAX@Z)".

client.cpp.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "" int __cdecl dlclose(void *)" (?dlclose@@YAHPAX@Z)" in Funktion ""public: __thiscall CHelper_libKODI_adsp::~CHelper_libKODI_adsp(void)" (??1CHelper_libKODI_adsp@@QAE@XZ)".

client.cpp.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "" void \* __cdecl dlsym(void *,char const *)" (?dlsym@@YAPAXPAXPBD@Z)" in Funktion ""public: bool __thiscall CHelper_libKODI_adsp::RegisterMe(void *)" (?RegisterMe@CHelper_libKODI_adsp@@QAE_NPAX@Z)". 

client.cpp.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "" char \* __cdecl dlerror(void)" (?dlerror@@YAPADXZ)" in Funktion ""public: bool __thiscall CHelper_libKODI_adsp::RegisterMe(void *)" (?RegisterMe@CHelper_libKODI_adsp@@QAE_NPAX@Z)".

adsp.biquad.filters.dll : fatal error LNK1120: 4 nicht aufgel÷ste Externe

**Comment by AchimTuran** [comment]
@Montellese 
Here is the [full log](http://pastebin.com/DNjXVi09)

**Comment by Montellese** [comment]
You need to add libplatform as a required package as well and add it to include directories and as a dependency (see e.g. pvr.mythtv's CMakeLists.txt) because right now you don't link to it so it can't find the symbols during linking.

**Comment by AchimTuran** [comment]
@Montellese @opdenkamp 

> You need to add libplatform as a required package as well and add it to include directories and as a dependency (see e.g. pvr.mythtv's CMakeLists.txt) because right now you don't link to it so it can't find the symbols during linking.

You're right with your hints, now the build is successful here on windows.

From my side we can close/delete this PR.

Thanks for your help.

**Pull request closed without merging**
