### PR TITLE
add fallback libdir like in platform

### PR DESCRIPTION
**Pull request by a1rwulf**
Hey I found this when working on my OE build.
wsnipex gave me the hint to look in the platform repo for this fix.

### CODE REVIEW

**Comment by wsnipex** [comment]
looks fine, brings it in line with platform.

**Comment by wsnipex** [comment]
@herrnst, should we add something for gentoo here as well?

**Comment by herrnst** [comment]
While when installing via ebuild (packaging), "inherit cmake-utils" will add -DCMAKE_INSTALL_LIBDIR automatically, it might help for manual compilation. On gentoo, there is

```
# cat /etc/gentoo-release
Gentoo Base System release 2.2
```

So: On amd64, there's /usr/lib64, and i686 has /usr/lib (and their counterparts in /usr/local) - HTH.

**Comment by wsnipex** [comment]
@a1rwulf can you add this please?

**Comment by a1rwulf** [comment]
I'm in Montpellier til sunday, so I'll add it early next week.

**Comment by a1rwulf** [comment]
OK added.
According to above gentoo will behave just like fedora etc.
I have no gentoo installation so it's not testet!
Sorry for being quite late :)

**Comment by a1rwulf** [comment]
@wsnipex should the gentoo stuff go into "platform" too?

**Comment by wsnipex** [comment]
that would make sense yes.
thanks!

**Pull request merged**
