### PR TITLE
fix files still denoting p8-platform

### PR DESCRIPTION
**Pull request by mdeguzis**
2 files still noted as p8-platform

### CODE REVIEW

**Comment by Montellese** [comment]
I'm confused. Didn't you make those changes yourself in https://github.com/xbmc/kodi-platform/commit/1fdcd0ca6f214efbfd1d7ab66d881abdf5faa24f? There are 2 more occurances of `p8-platform` in the `CMakeLists.txt` so this is certainly not correct.
And `p8-platform` is the new name so that's what we want to have.

**Comment by mdeguzis** [comment]
If I package for Jarvis (even the RC to test), I was under the impression that the addons would still use the [old name](https://github.com/Pulse-Eight/platform/tree/oldname). I misunderstood the prior discussion about that, since the control file for the PVR addons note **>=** 16.0

In any case, apologies about the PR closing.

**Comment by wsnipex** [comment]
Jarvis does still use the old libplatform: https://github.com/xbmc/xbmc/blob/Jarvis/project/cmake/addons/depends/common/kodi-platform/kodi-platform.txt

Whats missing here is a jarvis branch up to this commit

**Comment by mdeguzis** [comment]
@wsnipex , can that be easily done here? If I build a set of  Kodi dependency packages (platform, kodi-platform etc.), having a Jarvis target here would make sense to me. A lot of the Kodi repositories have split branches currently for Isengard, Jarvis, and master. I didn't mean to stir up anything here, but I want to be sure the packages I am testing are using correct dependencies.

**Comment by wsnipex** [comment]
yep, done: https://github.com/xbmc/kodi-platform/commits/Jarvis

**Pull request closed without merging**
