### PR TITLE
use https://github.com/Pulse-Eight/platform as platform lib

### PR DESCRIPTION
**Pull request by opdenkamp**
goes with https://github.com/xbmc/xbmc/pull/6891

### CODE REVIEW

**Comment by FernetMenta** [comment]
why do you delete all this files here? a mirror is easier to handle than a zip file with the sources on our mirrors.

**Comment by opdenkamp** [comment]
It shouldn't have been in a "kodi-platform" in the first place, that was 
just temporary as part of the cmake pr. Those files belong to libCEC, 
and I've created a new libplatform that contains these now. It's a 
separate lib/header collection now. And we're not going to maintain 
copies of those in two different libs, that defeats the purpose.

**Comment by opdenkamp** [comment]
@wsnipex can you update the debs please

**Comment by opdenkamp** [comment]
@wsnipex you can also copy them from https://launchpad.net/~pulse-eight/+archive/ubuntu/testing/+packages if you like, fresh builds

**Comment by wsnipex** [comment]
already built, had to fix up the build script anyway. Please note https://github.com/xbmc/kodi-platform/pull/6 for future reference.

**Comment by opdenkamp** [comment]
right, missed that file, sorry.
the platform lib (not kodi-platform) got updated and the build-deps ppa still contains the old one. it's 1.0.5-1 now

**Comment by wsnipex** [comment]
copied to build-deps ppa as well

**Comment by Montellese** [comment]
Why did you remove `StringUtils.h/.cpp`? It doesn't seem to be used in any of the other files you removed and it's not platform-dependent (which is what libplatform is about IIRC).

**Comment by opdenkamp** [comment]
yeah, wasn't sure about that one. it's adding something to the platform, similar to StringUtils, which wasn't tied to Kodi and used by libCEC before 3.0, so I put it there, but I've removed all uses of it in libCEC now in favour of StringUtils.

@EricV2 take build issues to the forum please, the PR builds fine.

**Pull request merged**
